// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_srv_uc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Uc service

type UcService interface {
	CreateUser(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	DeleteUser(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type ucService struct {
	c    client.Client
	name string
}

func NewUcService(name string, c client.Client) UcService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.uc"
	}
	return &ucService{
		c:    c,
		name: name,
	}
}

func (c *ucService) CreateUser(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Uc.CreateUser", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ucService) DeleteUser(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Uc.DeleteUser", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Uc service

type UcHandler interface {
	CreateUser(context.Context, *User, *Response) error
	DeleteUser(context.Context, *Request, *Response) error
}

func RegisterUcHandler(s server.Server, hdlr UcHandler, opts ...server.HandlerOption) error {
	type uc interface {
		CreateUser(ctx context.Context, in *User, out *Response) error
		DeleteUser(ctx context.Context, in *Request, out *Response) error
	}
	type Uc struct {
		uc
	}
	h := &ucHandler{hdlr}
	return s.Handle(s.NewHandler(&Uc{h}, opts...))
}

type ucHandler struct {
	UcHandler
}

func (h *ucHandler) CreateUser(ctx context.Context, in *User, out *Response) error {
	return h.UcHandler.CreateUser(ctx, in, out)
}

func (h *ucHandler) DeleteUser(ctx context.Context, in *Request, out *Response) error {
	return h.UcHandler.DeleteUser(ctx, in, out)
}
