// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_srv_uc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Pwd                  string   `protobuf:"bytes,4,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	UseFlag              int32    `protobuf:"varint,7,opt,name=useFlag,proto3" json:"useFlag,omitempty"`
	CreateTime           int64    `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,9,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetUseFlag() int32 {
	if m != nil {
		return m.UseFlag
	}
	return 0
}

func (m *User) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *User) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type Request struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Response struct {
	User                 *User             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Users                []*User           `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Errors               []*Error          `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	Code                 int32             `protobuf:"varint,6,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string            `protobuf:"bytes,7,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string            `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	ResultMap            map[string]string `protobuf:"bytes,9,rep,name=resultMap,proto3" json:"resultMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Response) GetResultMap() map[string]string {
	if m != nil {
		return m.ResultMap
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "go.micro.srv.uc.User")
	proto.RegisterType((*Request)(nil), "go.micro.srv.uc.Request")
	proto.RegisterType((*Error)(nil), "go.micro.srv.uc.Error")
	proto.RegisterType((*Response)(nil), "go.micro.srv.uc.Response")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.srv.uc.Response.ResultMapEntry")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x5d, 0x6b, 0xd5, 0x40,
	0x10, 0x35, 0x9f, 0xb7, 0x99, 0x42, 0x2d, 0x83, 0x2d, 0xdb, 0x3e, 0x48, 0xc8, 0x53, 0x44, 0x88,
	0x50, 0x5f, 0x44, 0x14, 0x84, 0xda, 0xbe, 0xf9, 0xb2, 0xd8, 0x1f, 0xb0, 0x26, 0x43, 0x0d, 0x26,
	0xd9, 0xb8, 0xbb, 0xb9, 0xd2, 0xdf, 0xe0, 0xbf, 0xf3, 0xd1, 0x5f, 0x23, 0x3b, 0x49, 0xec, 0xb5,
	0x1f, 0xbe, 0xdc, 0x7b, 0xe6, 0xcc, 0xc9, 0xce, 0x9e, 0x93, 0x09, 0x1c, 0x8d, 0x46, 0x3b, 0xfd,
	0x6a, 0xb2, 0x64, 0xf8, 0xa7, 0xe2, 0x1a, 0x9f, 0x5e, 0xeb, 0xaa, 0x6f, 0x6b, 0xa3, 0x2b, 0x6b,
	0xb6, 0xd5, 0x54, 0x17, 0xbf, 0x03, 0x88, 0xaf, 0x2c, 0x19, 0x3c, 0x80, 0xb0, 0x6d, 0x44, 0x90,
	0x07, 0x65, 0x26, 0xc3, 0xb6, 0x41, 0x84, 0x78, 0x50, 0x3d, 0x89, 0x90, 0x19, 0xc6, 0xf8, 0x0c,
	0x92, 0xf1, 0xab, 0x1e, 0x48, 0x44, 0x4c, 0xce, 0x05, 0x1e, 0x42, 0x34, 0xfe, 0x68, 0x44, 0xcc,
	0x9c, 0x87, 0x5e, 0x47, 0xbd, 0x6a, 0x3b, 0x91, 0xcc, 0x3a, 0x2e, 0xf0, 0x18, 0x52, 0xb5, 0x55,
	0x4e, 0x19, 0x91, 0x32, 0xbd, 0x54, 0x28, 0x60, 0x33, 0x59, 0xba, 0xec, 0xd4, 0xb5, 0xd8, 0xe4,
	0x41, 0x99, 0xc8, 0xb5, 0xc4, 0xe7, 0x00, 0xb5, 0x21, 0xe5, 0xe8, 0x73, 0xdb, 0x93, 0xd8, 0xcb,
	0x83, 0x32, 0x92, 0x3b, 0x8c, 0xef, 0x4f, 0x63, 0xb3, 0xf6, 0xb3, 0xb9, 0x7f, 0xcb, 0x14, 0x27,
	0xb0, 0x91, 0xf4, 0x7d, 0x22, 0xeb, 0xee, 0xda, 0x2b, 0xde, 0x43, 0x72, 0x61, 0x8c, 0x36, 0xde,
	0x67, 0xad, 0x1b, 0xe2, 0x56, 0x22, 0x19, 0x63, 0x0e, 0xfb, 0x0d, 0xd9, 0xda, 0xb4, 0xa3, 0x6b,
	0xf5, 0xb0, 0x44, 0xb0, 0x4b, 0x15, 0xbf, 0x42, 0xd8, 0x93, 0x64, 0x47, 0x3d, 0x58, 0xc2, 0x17,
	0x10, 0xfb, 0x88, 0xf9, 0x88, 0xfd, 0xb3, 0xa3, 0xea, 0x4e, 0xc6, 0x95, 0xcf, 0x57, 0xb2, 0x04,
	0x5f, 0x42, 0xe2, 0xff, 0xad, 0x08, 0xf3, 0xe8, 0x71, 0xed, 0xac, 0xc1, 0x0a, 0x52, 0xf2, 0x77,
	0xb4, 0x22, 0x61, 0xf5, 0xf1, 0x3d, 0x35, 0x5b, 0x90, 0x8b, 0xea, 0xaf, 0x95, 0x74, 0xc7, 0xca,
	0x21, 0x44, 0xbd, 0x9d, 0x83, 0xcd, 0xa4, 0x87, 0x5e, 0xd5, 0x28, 0xa7, 0x38, 0xce, 0x4c, 0x32,
	0xc6, 0x4b, 0xc8, 0x0c, 0xd9, 0xa9, 0x73, 0x9f, 0xd4, 0x28, 0x32, 0x1e, 0x56, 0xde, 0x1b, 0xb6,
	0xfa, 0xf5, 0x60, 0x96, 0x5e, 0x0c, 0xce, 0xdc, 0xc8, 0xdb, 0x47, 0x4f, 0xdf, 0xc1, 0xc1, 0xbf,
	0x4d, 0x3f, 0xff, 0x1b, 0xdd, 0x2c, 0xc1, 0x7b, 0xe8, 0x97, 0x63, 0xab, 0xba, 0x69, 0xdd, 0xac,
	0xb9, 0x78, 0x1b, 0xbe, 0x09, 0xce, 0x7e, 0x06, 0x10, 0x5e, 0xd5, 0xf8, 0x01, 0xe0, 0x9c, 0xdf,
	0x31, 0xef, 0xe5, 0xc3, 0x11, 0x9d, 0x9e, 0x3c, 0x7a, 0xbd, 0xe2, 0x09, 0x9e, 0x03, 0x7c, 0xa4,
	0x8e, 0x96, 0x13, 0xc4, 0x03, 0x52, 0x5e, 0x8a, 0xff, 0x1e, 0xf2, 0x25, 0xe5, 0x2f, 0xe6, 0xf5,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x5a, 0xe1, 0x48, 0x4a, 0x03, 0x00, 0x00,
}
