version: '3.1'

services:

  api-server:
    image: microhq/micro
    ports: 
      - 8080:8080
    environment: 
      MICRO_REGISTRY: "mdns"
    command: api --handler=rpc --address=:8080 --namespace=go.micro.srv
    depends_on:
      - dotc-service
      - block-service

  dotc-service:
    image: dotc-srv
    restart: always
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - database

  block-service:
    image: block-srv
    restart: always
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      IPFS_URL: "120.76.199.16:9095"
    depends_on:
      - dotc-service

  # datastore:
  #   image: mongo
  #   hostname: datastore
  #   ports:
  #     - 27017:27017

  database:
    image: postgres
    hostname: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"      

networks:
  default:
    external:
      name: otm