version: '3.1'

services:

  # api-server:
  #   image: microhq/micro
  #   ports: 
  #     - 8080:8080
  #   environment: 
  #     MICRO_REGISTRY: "mdns"

  user-service:
    image: dotc-srv
    restart: always
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      - database

  # datastore:
  #   image: mongo
  #   hostname: datastore
  #   ports:
  #     - 27017:27017

  database:
    image: postgres
    hostname: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"      

networks:
  default:
    external:
      name: otm