// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/uc/uc.proto

package go_micro_srv_uc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Pwd                  string   `protobuf:"bytes,4,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	UseFlag              int32    `protobuf:"varint,7,opt,name=useFlag,proto3" json:"useFlag,omitempty"`
	CreateTime           int64    `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,9,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_045aa24dd64effcb, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetUseFlag() int32 {
	if m != nil {
		return m.UseFlag
	}
	return 0
}

func (m *User) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *User) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type BlockAccount struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Mnemonic             string   `protobuf:"bytes,3,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	NodeAddress          string   `protobuf:"bytes,5,opt,name=nodeAddress,proto3" json:"nodeAddress,omitempty"`
	NodeFlag             int32    `protobuf:"varint,6,opt,name=nodeFlag,proto3" json:"nodeFlag,omitempty"`
	Remark               string   `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateTime           int64    `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           int64    `protobuf:"varint,9,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockAccount) Reset()         { *m = BlockAccount{} }
func (m *BlockAccount) String() string { return proto.CompactTextString(m) }
func (*BlockAccount) ProtoMessage()    {}
func (*BlockAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_045aa24dd64effcb, []int{1}
}

func (m *BlockAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockAccount.Unmarshal(m, b)
}
func (m *BlockAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockAccount.Marshal(b, m, deterministic)
}
func (m *BlockAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockAccount.Merge(m, src)
}
func (m *BlockAccount) XXX_Size() int {
	return xxx_messageInfo_BlockAccount.Size(m)
}
func (m *BlockAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockAccount.DiscardUnknown(m)
}

var xxx_messageInfo_BlockAccount proto.InternalMessageInfo

func (m *BlockAccount) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BlockAccount) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *BlockAccount) GetMnemonic() string {
	if m != nil {
		return m.Mnemonic
	}
	return ""
}

func (m *BlockAccount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BlockAccount) GetNodeAddress() string {
	if m != nil {
		return m.NodeAddress
	}
	return ""
}

func (m *BlockAccount) GetNodeFlag() int32 {
	if m != nil {
		return m.NodeFlag
	}
	return 0
}

func (m *BlockAccount) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *BlockAccount) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *BlockAccount) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

type Request struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_045aa24dd64effcb, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Request) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_045aa24dd64effcb, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Response struct {
	User                 *User             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Users                []*User           `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Account              *BlockAccount     `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Accounts             []*BlockAccount   `protobuf:"bytes,4,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Errors               []*Error          `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	Code                 int32             `protobuf:"varint,6,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string            `protobuf:"bytes,7,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string            `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	ResultMap            map[string]string `protobuf:"bytes,9,rep,name=resultMap,proto3" json:"resultMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_045aa24dd64effcb, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Response) GetAccount() *BlockAccount {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *Response) GetAccounts() []*BlockAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Response) GetResultMap() map[string]string {
	if m != nil {
		return m.ResultMap
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "go.micro.srv.uc.User")
	proto.RegisterType((*BlockAccount)(nil), "go.micro.srv.uc.BlockAccount")
	proto.RegisterType((*Request)(nil), "go.micro.srv.uc.Request")
	proto.RegisterType((*Error)(nil), "go.micro.srv.uc.Error")
	proto.RegisterType((*Response)(nil), "go.micro.srv.uc.Response")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.srv.uc.Response.ResultMapEntry")
}

func init() { proto.RegisterFile("proto/uc/uc.proto", fileDescriptor_045aa24dd64effcb) }

var fileDescriptor_045aa24dd64effcb = []byte{
	// 577 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x6e, 0xd4, 0x3c,
	0x10, 0xfd, 0x92, 0xdd, 0xcd, 0xee, 0x4e, 0x3f, 0x95, 0xd6, 0x82, 0xca, 0x54, 0x02, 0xad, 0xf6,
	0x6a, 0x11, 0x52, 0x2a, 0xca, 0x05, 0x3f, 0x02, 0x89, 0xfe, 0x4a, 0x45, 0x42, 0x42, 0x16, 0x7d,
	0x00, 0x63, 0x8f, 0x4a, 0xd4, 0x24, 0x0e, 0x76, 0x52, 0xd4, 0x47, 0xe2, 0x45, 0x78, 0x08, 0x9e,
	0x85, 0x0b, 0xe4, 0x89, 0x77, 0x9b, 0xb2, 0xed, 0x82, 0xe0, 0x2a, 0xe7, 0x8c, 0xcf, 0x8c, 0x7d,
	0x66, 0xec, 0xc0, 0x66, 0x65, 0x4d, 0x6d, 0x76, 0x1a, 0xb5, 0xd3, 0xa8, 0x94, 0x30, 0xbb, 0x73,
	0x66, 0xd2, 0x22, 0x53, 0xd6, 0xa4, 0xce, 0x5e, 0xa4, 0x8d, 0x9a, 0x7e, 0x8f, 0xa0, 0x7f, 0xea,
	0xd0, 0xb2, 0x75, 0x88, 0x33, 0xcd, 0xa3, 0x49, 0x34, 0x1b, 0x8b, 0x38, 0xd3, 0x8c, 0x41, 0xbf,
	0x94, 0x05, 0xf2, 0x98, 0x22, 0x84, 0xd9, 0x5d, 0x18, 0x54, 0x9f, 0x4c, 0x89, 0xbc, 0x47, 0xc1,
	0x96, 0xb0, 0x0d, 0xe8, 0x55, 0x5f, 0x34, 0xef, 0x53, 0xcc, 0x43, 0xaf, 0xc3, 0x42, 0x66, 0x39,
	0x1f, 0xb4, 0x3a, 0x22, 0x6c, 0x0b, 0x12, 0x79, 0x21, 0x6b, 0x69, 0x79, 0x42, 0xe1, 0xc0, 0x18,
	0x87, 0x61, 0xe3, 0xf0, 0x38, 0x97, 0x67, 0x7c, 0x38, 0x89, 0x66, 0x03, 0x31, 0xa7, 0xec, 0x21,
	0x80, 0xb2, 0x28, 0x6b, 0xfc, 0x90, 0x15, 0xc8, 0x47, 0x93, 0x68, 0xd6, 0x13, 0x9d, 0x88, 0x5f,
	0x6f, 0x2a, 0x3d, 0x5f, 0x1f, 0xb7, 0xeb, 0x57, 0x91, 0xe9, 0x8f, 0x08, 0xfe, 0xdf, 0xcf, 0x8d,
	0x3a, 0xdf, 0x53, 0xca, 0x34, 0x65, 0xbd, 0x64, 0x72, 0x0b, 0x92, 0xc6, 0xa1, 0x3d, 0xd1, 0xc1,
	0x66, 0x60, 0x6c, 0x1b, 0x46, 0x45, 0x89, 0x85, 0x29, 0x33, 0x15, 0xbc, 0x2e, 0xf8, 0xa2, 0x31,
	0xfd, 0x4e, 0x63, 0x26, 0xb0, 0x56, 0x1a, 0x8d, 0x7b, 0x5a, 0x5b, 0x74, 0x2e, 0xd8, 0xee, 0x86,
	0x7c, 0x45, 0x4f, 0xc9, 0x65, 0x42, 0x2e, 0x17, 0xdc, 0x9f, 0xc2, 0x62, 0x21, 0xed, 0x39, 0xf9,
	0x1f, 0x8b, 0xc0, 0xfe, 0xd9, 0xfe, 0x13, 0x18, 0x0a, 0xfc, 0xdc, 0xa0, 0xfb, 0x63, 0xe3, 0xd3,
	0xd7, 0x30, 0x38, 0xb2, 0xd6, 0x58, 0xef, 0x52, 0x19, 0x8d, 0x94, 0x32, 0x10, 0x84, 0xbd, 0x4b,
	0x8d, 0x4e, 0xd9, 0xac, 0xaa, 0x33, 0x53, 0x86, 0xcc, 0x6e, 0x68, 0xfa, 0xad, 0x07, 0x23, 0x81,
	0xae, 0x32, 0xa5, 0x43, 0xf6, 0x08, 0xfa, 0xbe, 0x2a, 0x95, 0x58, 0xdb, 0xbd, 0x97, 0xfe, 0x72,
	0xf5, 0x52, 0x7f, 0xed, 0x04, 0x49, 0xd8, 0x63, 0x18, 0xf8, 0xaf, 0xe3, 0xf1, 0xa4, 0x77, 0xbb,
	0xb6, 0xd5, 0xb0, 0x67, 0x30, 0x94, 0xed, 0x3c, 0x69, 0x36, 0x6b, 0xbb, 0x0f, 0x96, 0xe4, 0xdd,
	0xa1, 0x8b, 0xb9, 0x9a, 0xbd, 0x80, 0x51, 0x80, 0x8e, 0xf7, 0x69, 0xa3, 0xdf, 0x64, 0x2e, 0xe4,
	0x2c, 0x85, 0x04, 0x7d, 0x5f, 0xfc, 0x6c, 0x7d, 0xe2, 0xd6, 0x52, 0x22, 0xb5, 0x4d, 0x04, 0xd5,
	0xa2, 0x7d, 0x49, 0xa7, 0x7d, 0x1b, 0xd0, 0x2b, 0xdc, 0x59, 0x98, 0xb1, 0x87, 0x5e, 0xa5, 0x65,
	0x2d, 0x69, 0xb4, 0x63, 0x41, 0x98, 0x1d, 0xc3, 0xd8, 0xa2, 0x6b, 0xf2, 0xfa, 0x9d, 0xac, 0xf8,
	0x98, 0x36, 0x9b, 0x2d, 0x6d, 0x36, 0xef, 0xb1, 0x07, 0xad, 0xf4, 0xa8, 0xac, 0xed, 0xa5, 0xb8,
	0x4a, 0xdd, 0x7e, 0x05, 0xeb, 0xd7, 0x17, 0xfd, 0xfe, 0xe7, 0x78, 0x19, 0x2e, 0x81, 0x87, 0xfe,
	0x9d, 0x5e, 0xc8, 0xbc, 0x99, 0x3f, 0xf2, 0x96, 0xbc, 0x8c, 0x9f, 0x47, 0xbb, 0x5f, 0x63, 0x88,
	0x4f, 0x15, 0x7b, 0x03, 0x70, 0x40, 0xf7, 0x8d, 0x7e, 0x11, 0x37, 0x8f, 0x65, 0xfb, 0xfe, 0xad,
	0xc7, 0x9b, 0xfe, 0xc7, 0x0e, 0x00, 0x0e, 0x31, 0xc7, 0x50, 0x81, 0xdf, 0x20, 0xa5, 0x0b, 0xba,
	0xba, 0xc8, 0x7b, 0x60, 0xed, 0x31, 0xae, 0x3d, 0xe6, 0xd5, 0xc3, 0x5b, 0x5d, 0xf1, 0x2d, 0x6c,
	0x1e, 0x67, 0xa5, 0x0e, 0x5a, 0xb7, 0x7f, 0x79, 0x7a, 0x72, 0xf8, 0x97, 0xa7, 0xfb, 0x98, 0xd0,
	0xaf, 0xf5, 0xe9, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x65, 0x28, 0xa2, 0x6f, 0x05, 0x00,
	0x00,
}
